#!/bin/bash
dist=$1
img=$2

if [[ x$1 == x || x$2 == x ]]; then
    echo "Usage: $0 dist img"
    exit 1
fi

if [[ -e $img ]]; then
    echo "$img exists: exiting"
    exit 0
fi

if [[ -e $img.bz2 ]]; then
    echo "Uncompressing $img.bz2"
    bzip2 -d -c $img.bz2 > $img
    exit 0
fi

sudo apt-get install python-vm-builder
sudo vmbuilder kvm ubuntu \
    -v -o -d $dist \
    --arch=amd64 \
    --iso=$HOME/ubuntu-9.10-server-amd64.iso \
    --mirror=http://fr.archive.ubuntu.com/ubuntu \
    --suite=$dist \
    --flavour=generic \
    --hostname=cotson \
    --user=user --name=user --pass=user \
    --rootpass=root \
    --rootsize=1024 \
    --swapsize=32 \
    --addpkg=build-essential

# --in-place \
# --variant=minbase \

kvm-img convert -O raw $dist/disk0.qcow2 $img
bzip2 -9 -c $img > $img.bz2

